FROM node:latest as build

WORKDIR /var/www/memory_wall_frontend

COPY . .

RUN npm install

RUN npm run build


FROM nginx:latest

COPY --from=build  /var/www/memory_wall_frontend/dist/the-memory-wall-frontend/browser /usr/share/nginx/html
COPY docker/nginx/ /etc/nginx/conf.d/